# Generated by Django 5.0.7 on 2026-05-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("meter_number", models.CharField(blank=True, max_length=80)),
                ("service_address", models.CharField(blank=True, max_length=255)),
                ("grid_region", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP"),
                            ("utility", "Utility"),
                            ("travel", "Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("completed", "Completed"),
                            ("completed_with_flags", "Completed with flags"),
                            ("failed", "Failed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("total_rows", models.PositiveIntegerField()),
                ("normalized_rows", models.PositiveIntegerField()),
                ("failed_rows", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=60)),
                ("scope", models.CharField(max_length=20)),
                ("unit", models.CharField(max_length=40)),
                (
                    "kg_co2e_per_unit",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("source", models.CharField(max_length=180)),
                ("region", models.CharField(blank=True, max_length=80)),
                ("active", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["activity_type", "region"],
                "unique_together": {("activity_type", "scope", "unit", "region")},
            },
        ),
        migrations.CreateModel(
            name="NormalizedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP"),
                            ("utility", "Utility"),
                            ("travel", "Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=120)),
                ("activity_type", models.CharField(max_length=60)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("scope_1", "Scope 1"),
                            ("scope_2", "Scope 2"),
                            ("scope_3", "Scope 3"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normalized", "Normalized"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("locked", "Locked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "original_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("original_unit", models.CharField(blank=True, max_length=40)),
                (
                    "normalized_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("normalized_unit", models.CharField(blank=True, max_length=40)),
                ("location_label", models.CharField(blank=True, max_length=180)),
                ("department", models.CharField(blank=True, max_length=120)),
                ("counterparty", models.CharField(blank=True, max_length=160)),
                ("currency", models.CharField(blank=True, max_length=3)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "emissions_kg_co2e",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("normalized_payload", models.JSONField()),
                ("edited_fields", models.JSONField()),
                ("edit_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="review.ingestionbatch",
                    ),
                ),
                (
                    "emission_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="review.emissionfactor",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="review.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="ingestionbatch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="review.organization"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="review.organization"
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=40)),
                ("actor_name", models.CharField(max_length=120)),
                ("changes", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.ingestionbatch",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="review.normalizedactivity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("source_payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("parsed", "Parsed"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("parse_errors", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="review.ingestionbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["batch_id", "row_number"],
                "unique_together": {("batch", "row_number")},
            },
        ),
        migrations.AddField(
            model_name="normalizedactivity",
            name="raw_record",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="review.rawrecord",
            ),
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                ("field", models.CharField(blank=True, max_length=80)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="review.normalizedactivity",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "code"],
            },
        ),
        migrations.CreateModel(
            name="SourceSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sap", "SAP"),
                            ("utility", "Utility"),
                            ("travel", "Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["source_type", "name"],
                "unique_together": {("organization", "source_type", "name")},
            },
        ),
        migrations.AddField(
            model_name="ingestionbatch",
            name="source_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="review.sourcesystem"
            ),
        ),
        migrations.CreateModel(
            name="UnitConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=40)),
                ("source_unit", models.CharField(max_length=40)),
                ("target_unit", models.CharField(max_length=40)),
                ("multiplier", models.DecimalField(decimal_places=8, max_digits=18)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "unique_together": {("category", "source_unit", "target_unit")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="facility",
            unique_together={("organization", "code")},
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_code", models.CharField(max_length=40)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.facility",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="review.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "plant_code")},
            },
        ),
    ]
